project:
  type: website
  output-dir: docs

website:
  title: "GEOS 270"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: Modules/moduleInfo.qmd
        text: Course Modules
    right:
      - icon: github
        href: https://github.com/GEOS270
        aria-label: Quarto GitHub
        
  sidebar:
    - title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - index.qmd
      - section: "Lab Info"
        href: LabInfo/labInfo.qmd
        contents:
        - LabInfo/softwareAccess.qmd
        - LabInfo/geogComputers.qmd
      - acknowledgement.qmd
    - title: "Course Modules"
      style: "docked"
      background: light
      contents:
      - Modules/moduleInfo.qmd
      - section: "Module 1"
        href: Modules/1/lecture.qmd
        contents:
        - href: Modules/1/instructions.qmd
          text: Lab Instructions
        - href: Modules/1/questions.qmd
          text: Lab Questions
      - section: "Module 2"
        href: Modules/2/lecture.qmd
        contents:
        - href: Modules/2/instructions.qmd
          text: Lab Instructions
        - href: Modules/2/questions.qmd
          text: Lab Questions
      - section: "Module 3"
        href: Modules/3/lecture.qmd
        contents:
        - href: Modules/3/instructions.qmd
          text: Lab Instructions
        - href: Modules/3/questions.qmd
          text: Lab Questions
      - section: "Module 4"
        href: Modules/4/lecture.qmd
        contents:
        - href: Modules/4/instructions.qmd
          text: Lab Instructions
        - href: Modules/4/questions.qmd
          text: Lab Questions
      - section: "Module 5"
        href: Modules/5/lecture.qmd
        contents:
        - href: Modules/5/instructions.qmd
          text: Lab Instructions
        - href: Modules/5/questions.qmd
          text: Lab Questions
      - section: "Module 6"
        href: Modules/6/lecture.qmd
        contents:
        - href: Modules/6/instructions.qmd
          text: Lab Instructions
        - href: Modules/6/questions.qmd
          text: Lab Questions
      - section: "Module 7"
        href: Modules/7/lecture.qmd
        contents:
        - href: Modules/7/ExtraCredit.qmd
          text: Extra Credit
      - section: "Final Project"
        href: FinalProjectInstructions.qmd
        contents:
        - href: proposals/Final-Project-Proposal-Form.docx
          text: Proposal Form

  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:    
  #     - section: "Module 1"
  #       contents:
  #       - href: Modules/1/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/1/LabAssignment.qmd
  #         text: Lab Assignment    
  #     - section: "Module 2"
  #       contents:
  #       - href: Modules/2/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/2/LabAssignment.qmd
  #         text: Lab Assignment    
  #     - section: "Module 3"
  #       contents:
  #       - href: Modules/3/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/3/LabAssignment.qmd
  #         text: Lab Assignment  
  #     - section: "Module 4"
  #       contents:
  #       - href: Modules/4/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/4/LabAssignment.qmd
  #         text: Lab Assignment  
  #     - section: "Module 5"
  #       contents:
  #       - href: Modules/5/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/5/LabAssignment.qmd
  #         text: Lab Assignment  
  #     - section: "Module 6"
  #       contents:
  #       - href: Modules/6/LectureContent.qmd
  #         text: Lecture Slides
  #       - href: Modules/6/LabAssignment.qmd
  #         text: Lab Assignment
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
