---
title: "What is GIS and Where Did It Come From?"
format: html
echo: false
---

This module is intended to give a broad overview of the discipline and get you started using the ArcGIS Pro software package.


## Learning Outcomes


* Overview of the development of GIS
  * The first maps & surveys
  * Creation of map projections and spatial analysis methods
  * Development and proliferation of GIS technology
* Get your bearings with ArcGSI Pro software package
  * Introductory tutorials from ESRI
* Recreate a historical analysis using modern methods
  * Brief overview of digitizing and georeferencing
  * Introduction to spatial analysis
  * Create and share a map

# What is GIS?

Before we do anything else, we need to define GIS.

<div style="overflow: hidden;
  padding-top: 56.25%;
  position: relative">
  <iframe src="https://geos270.github.io/LectureSlides/What_is_GIS/Slides.html" title="Processes" scrolling="no" frameborder="0"
    style="border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;">
   <p>Your browser does not support iframes.</p>
 </iframe>
</div>
<a href="https://geos270.github.io/LectureSlides/What_is_GIS/Slides.html" target="_blank">View slides in new tab</a>


# History of GIS

The earliest maps presented diverse and abstract representations of reality.  They used very different medium than we do today today, and are sometimes quite difficult to see as maps today.  

<div style="overflow: hidden;
  padding-top: 56.25%;
  position: relative">
  <iframe src="https://geos270.github.io/LectureSlides/History_of_GIS/Slides.html" title="Processes" scrolling="no" frameborder="0"
    style="border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;">
   <p>Your browser does not support iframes.</p>
 </iframe>
</div>
<a href="https://geos270.github.io/LectureSlides/History_of_GIS/Slides.html" target="_blank">View slides in new tab</a>


# Modern GIS

GIS has become a powerful, widely used tool for GIS in recent decades.

<div style="overflow: hidden;
  padding-top: 56.25%;
  position: relative">
  <iframe src="https://geos270.github.io/LectureSlides/Modern_GIS/Slides.html" title="Processes" scrolling="no" frameborder="0"
    style="border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;">
   <p>Your browser does not support iframes.</p>
 </iframe>
</div>
<a href="https://geos270.github.io/LectureSlides/Modern_GIS/Slides.html" target="_blank">View slides in new tab</a>
