<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>GEOS 270 - Syllabus</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">GEOS 270</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Modules/moduleInfo.html">
 <span class="menu-text">Course Modules</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/GEOS270"><i class="bi bi-github" role="img" aria-label="Quarto GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Syllabus</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link active">Syllabus</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./LabInfo/labInfo.html" class="sidebar-item-text sidebar-link">Lab Info</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./LabInfo/softwareAccess.html" class="sidebar-item-text sidebar-link">ArcGIS Pro Access</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./LabInfo/geogComputers.html" class="sidebar-item-text sidebar-link">Using Geography Lab Computers</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowledgement.html" class="sidebar-item-text sidebar-link">Territorial and Cultural Acknowledgement</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  <li><a href="#important-information" id="toc-important-information" class="nav-link" data-scroll-target="#important-information">Important Information</a></li>
  <li><a href="#course-overview" id="toc-course-overview" class="nav-link" data-scroll-target="#course-overview">Course Overview</a>
  <ul class="collapse">
  <li><a href="#evaluation" id="toc-evaluation" class="nav-link" data-scroll-target="#evaluation">Evaluation</a>
  <ul class="collapse">
  <li><a href="#lab-assignments" id="toc-lab-assignments" class="nav-link" data-scroll-target="#lab-assignments">Lab Assignments</a></li>
  <li><a href="#final-project" id="toc-final-project" class="nav-link" data-scroll-target="#final-project">Final Project</a></li>
  <li><a href="#final-exam" id="toc-final-exam" class="nav-link" data-scroll-target="#final-exam">Final Exam</a></li>
  <li><a href="#lecture-participation" id="toc-lecture-participation" class="nav-link" data-scroll-target="#lecture-participation">Lecture Participation</a></li>
  <li><a href="#extra-credit" id="toc-extra-credit" class="nav-link" data-scroll-target="#extra-credit">Extra Credit</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#your-instructor" id="toc-your-instructor" class="nav-link" data-scroll-target="#your-instructor">Your Instructor</a></li>
  <li><a href="#course-policies" id="toc-course-policies" class="nav-link" data-scroll-target="#course-policies">Course Policies</a>
  <ul class="collapse">
  <li><a href="#feedback-deadlines" id="toc-feedback-deadlines" class="nav-link" data-scroll-target="#feedback-deadlines">Feedback &amp; Deadlines</a></li>
  <li><a href="#absences" id="toc-absences" class="nav-link" data-scroll-target="#absences">Absences</a></li>
  <li><a href="#accommodations" id="toc-accommodations" class="nav-link" data-scroll-target="#accommodations">Accommodations</a></li>
  <li><a href="#academic-concessions" id="toc-academic-concessions" class="nav-link" data-scroll-target="#academic-concessions">Academic Concessions</a></li>
  <li><a href="#academic-integrity" id="toc-academic-integrity" class="nav-link" data-scroll-target="#academic-integrity">Academic Integrity</a></li>
  </ul></li>
  <li><a href="#strategies-for-success" id="toc-strategies-for-success" class="nav-link" data-scroll-target="#strategies-for-success">Strategies for Success</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Syllabus</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>GEOS 270</strong>: 2023 S1 with Dr.&nbsp;June skeeter</p>
<hr>
<p>This course will introduce you to key concepts and tools used to collect, map, and interpret geographic data. We will learn how geospatial data can be used to aid decision-making, complement scientific analysis, assist with urban planning, and help inform policy-making. You will gain practical experience using geospatial data to solve problems in both the natural and human realms. This term we will cover:</p>
<section id="learning-outcomes" class="level1">
<h1>Learning Outcomes</h1>
<ul>
<li>How GIS functions and how it can be applied to solve problems.</li>
<li>How phenomena are represented as geospatial data in a GIS.</li>
<li>How to implement geospatial analysis methods.</li>
<li>Visualizing geospatial data and principles of good map design.</li>
<li>Sources of error in GIS analysis and output.</li>
<li>The ethical implications of GIS analysis.</li>
<li>GIS workflows and collaborating to complete a GIS project.</li>
</ul>
</section>
<section id="important-information" class="level1">
<h1>Important Information</h1>
<table class="table">
<tbody>
<tr class="odd">
<td>Lecture</td>
<td style="text-align: left;">Tuesday &amp; Thursday, 12:00 - 14:00 in room 101</td>
</tr>
<tr class="even">
<td>Remote Attendance</td>
<td style="text-align: left;"><a href="https://ubc.zoom.us/j/68713181849?pwd=SThIWUkvVTVtbkpwME11c1NDYlFVZz09">Via zoom</a></td>
</tr>
<tr class="odd">
<td>Lecture Recordings</td>
<td style="text-align: left;">View <a href="https://drive.google.com/drive/folders/1bFWXslXnAQC5SIYX6z3dLyhtGzwQ3k98?usp=sharing">here</a></td>
</tr>
<tr class="even">
<td>TopHat Join Code</td>
<td style="text-align: left;"><p>495132</p></td>
</tr>
<tr class="odd">
<td>Piazza Page</td>
<td style="text-align: left;">Find it <a href="https://piazza.com/ubc.ca/summer2023/geos270">here</a></td>
</tr>
</tbody>
</table>
</section>
<section id="course-overview" class="level1">
<h1>Course Overview</h1>
<p>The course is arranged in a modular format, with due dates for each module shown in the schedule below. The modules are designed to introduce and cover specific topics within GIS, and are published as separate webpages.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-schedule" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;1: Important Dates</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 65%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Module</th>
<th style="text-align: left;">Topic</th>
<th style="text-align: left;">Due Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Module 1</td>
<td style="text-align: left;">History of GIS &amp; Intro to ArcGIS Pro</td>
<td style="text-align: left;">May 22</td>
</tr>
<tr class="even">
<td style="text-align: left;">Module 2</td>
<td style="text-align: left;">Coordinate Reference Systems</td>
<td style="text-align: left;">May 26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Module 3</td>
<td style="text-align: left;">Data Types, Data Classification, &amp; Data Visualization</td>
<td style="text-align: left;">June 31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Module 4</td>
<td style="text-align: left;">Spatial Data Models</td>
<td style="text-align: left;">June 7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Module 5</td>
<td style="text-align: left;">GIS Workflows, Spatial Analysis Methods</td>
<td style="text-align: left;">June 14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Module 6</td>
<td style="text-align: left;">Final Project Proposal, Spatial Sampling, Uncertainty, &amp; Ethics</td>
<td style="text-align: left;">June 19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Module 7</td>
<td style="text-align: left;">Final Project, Extra Credit Programming Exercise, &amp; Exam Review</td>
<td style="text-align: left;">June 27</td>
</tr>
<tr class="even">
<td style="text-align: left;">Final Exam</td>
<td style="text-align: left;">Asynchronous on Canvas</td>
<td style="text-align: left;">June 28</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="evaluation" class="level2">
<h2 class="anchored" data-anchor-id="evaluation">Evaluation</h2>
<p>Lab quizzes will make up the largest portion of your grade, followed by the final exam and final project which will be weighted equally, with Lecture Participation (via TopHat) making up the rest of your grade.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-grades" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;2: Components of your final grade</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Points Distribution</th>
<th style="text-align: left;">Total Points</th>
<th style="text-align: left;">Percent of Final Grade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lab Assignments (Top 5)</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">40%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Final Project</td>
<td style="text-align: left;">250</td>
<td style="text-align: left;">25%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Final Exam</td>
<td style="text-align: left;">250</td>
<td style="text-align: left;">25%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lecture Participation</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">10%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extra Credit</td>
<td style="text-align: left;">TBD</td>
<td style="text-align: left;">~</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="lab-assignments" class="level3">
<h3 class="anchored" data-anchor-id="lab-assignments">Lab Assignments</h3>
<p>The first six modules each have a lab assignment. Lab instructions are included on this website in each module’s pages (e.g., see <a href="./Modules/1/instructions.html">Lab 1 instructions here</a>). Each lab assignment has a corresponding set of questions (e.g., see <a href="./Modules/1/questions.html">Lab 1 questions here</a>). Take note of the answers as you work through the lab then submit you answers to canvas afterwards.</p>
<ul>
<li>Everyone gets one <strong>“free pass”</strong>: your lowest scoring lab quiz will be dropped at the end of term.</li>
</ul>
</section>
<section id="final-project" class="level3">
<h3 class="anchored" data-anchor-id="final-project">Final Project</h3>
<p>GIS is a collaborative discipline so your final project will be a group assignment (2-4 members). The project can be on any topic you choose, but I will also provide you with a set of project ideas to help get you started. More info will be provided later in the term.</p>
</section>
<section id="final-exam" class="level3">
<h3 class="anchored" data-anchor-id="final-exam">Final Exam</h3>
<p>The final exam will be will be cumulative, drawing from both lecture and lab material. It will consist of a flowchart question illustrating how to complete a GIS task, essays/short answers, and miscellaneous fill in the blanks, matching, multiple choice, etc. type questions. It will be asynchronous over Canvas and is scheduled for <strong>June 28</strong>. More info will be available closer to the exam date.</p>
</section>
<section id="lecture-participation" class="level3">
<h3 class="anchored" data-anchor-id="lecture-participation">Lecture Participation</h3>
<p>Lectures are held in person Tuesday &amp; Thursday, 12:00 - 14:00 in room 101 with a remote attendance option available on <a href="https://ubc.zoom.us/j/68713181849?pwd=SThIWUkvVTVtbkpwME11c1NDYlFVZz09">on zoom</a>. Recordings will be made available <a href="https://drive.google.com/drive/folders/1bFWXslXnAQC5SIYX6z3dLyhtGzwQ3k98?usp=sharing">here</a> for convenience, but lecture participation points are only available <strong>during</strong> keyInfo.</p>
<p>Lecture participation will be gauged using <a href="https://tophat.com/students/">TopHat</a>. The course <strong>Join Code</strong> is: <strong>495132</strong>.</p>
<ul>
<li>TopHat questions can <strong>only</strong> be answered during the lecture session
<ul>
<li>They will be available to in person and remote attendees</li>
<li>They can be answered via mobile device or laptop</li>
</ul></li>
<li>Questions will be marked based on participation (50%) and correctness (50%)
<ul>
<li>Anonymized answers will be reviewed in lecture to help gauge comprehension</li>
</ul></li>
</ul>
</section>
<section id="extra-credit" class="level3">
<h3 class="anchored" data-anchor-id="extra-credit">Extra Credit</h3>
<p>Extra credit will offered at multiple points through the term.</p>
<ul>
<li>The course also has a <a href="https://piazza.com/ubc.ca/summer2023/geos270">piazza</a> page which can be used to ask/answer questions about assignments and course materials. Students who are active and helpful on the piazza page will be offered extra participation credit at the end of term.</li>
<li>An extra credit programming exercise at the end of term will give you an opportunity to try you hand at GIS Programming</li>
<li>Final project proposal early submissions will receive extra credit as well</li>
</ul>
</section>
</section>
</section>
<section id="your-instructor" class="level1">
<h1>Your Instructor</h1>
<div class="columns">
<div class="column" style="width:30%;">
<p><img src="images/June.jpg" class="img-fluid" style="width:85.0%"></p>
</div><div class="column" style="width:70%;">
<table class="table">
<tbody>
<tr class="odd">
<td>Name</td>
<td style="text-align: left;"><p>Dr.&nbsp;June skeeter</p></td>
</tr>
<tr class="even">
<td>Pronouns</td>
<td style="text-align: left;"><p>They/Them/Theirs</p></td>
</tr>
<tr class="odd">
<td>Email</td>
<td style="text-align: left;"><p>june.skeeter@ubc.ca</p></td>
</tr>
<tr class="even">
<td>Office Hours</td>
<td style="text-align: left;"><p>Room 144, Geography Bldg Office hours after lecture</p></td>
</tr>
<tr class="odd">
<td>Zoom Office Hours</td>
<td style="text-align: left;"><p>By Appointment <strong>with at least 24 hr notice</strong> <a href="https://ubc.zoom.us/j/66359522453?pwd=ZzZUMzV3NVY1V3pzcmYzZFBadW93UT09">Office Hours Link</a></p></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>My name is June. I am a non-binary geographer, researcher, and educator who has been living as an uninvited guest on unceded Coast Salish Territory since 2015. I have been teaching GEOS 270 since 2020. I am passionate about teaching Geographic Information Science and using Geographic Information Systems as a tool to address social and ecological justice issues. My principal aim this semester is to provide a holistic introduction to the study of Geographic Information Science and application of Geographic Information Systems. I use GIS extensively is my research on climate change in the wetland ecosystems working as a Postdoc for the UBC Micrometeorology Lab. We study carbon balances in wetland ecosystems in the Metro Vancouver area.</p>
</section>
<section id="course-policies" class="level1">
<h1>Course Policies</h1>
<p>My aim for this semester is to provide a flexible and supportive learning environment while respecting the boundaries of myself and your TAs. These course policies are intended to establish a framework for navigating the course.</p>
<section id="feedback-deadlines" class="level2">
<h2 class="anchored" data-anchor-id="feedback-deadlines">Feedback &amp; Deadlines</h2>
<p>Lab assignments will be marked by your TA using a standard rubric. Short comments will be provided where applicable on written answers &amp; map submissions. Submissions will be accepted without late penalty for 4 days after their due date.</p>
<ul>
<li>Quizzes submitted <strong>by the due date</strong> will be graded and returned with feedback 4 days of the due date.</li>
<li>Late submissions <strong>waive their right</strong> to prompt grading/feedback.
<ul>
<li>Late quiz submissions <strong>will not</strong> receive written feedback from your TA.</li>
<li>Late quiz submissions will be marked whenever is convenient for your TA, which could be as late as the end of term</li>
<li>After the 4 day grace period, the quiz submission window will <strong>close</strong>, no exceptions.</li>
</ul></li>
<li>This policy only applies to the lab quizzes, <strong>not</strong> the final project or exam.</li>
</ul>
</section>
<section id="absences" class="level2">
<h2 class="anchored" data-anchor-id="absences">Absences</h2>
<p>If you are sick (with COVID or otherwise), please stay home to protect others and take care of yourself. Lectures are streamed <a href="https://ubc.zoom.us/j/68713181849?pwd=SThIWUkvVTVtbkpwME11c1NDYlFVZz09">on zoom</a> so that you may still attend online and get TopHat participation credit. Lecture recordings are also <a href="https://drive.google.com/drive/folders/1bFWXslXnAQC5SIYX6z3dLyhtGzwQ3k98?usp=sharing">here</a>. If you miss a lab session, you can attend an alternate session, just make sure to check in with TA running that session.</p>
</section>
<section id="accommodations" class="level2">
<h2 class="anchored" data-anchor-id="accommodations">Accommodations</h2>
<p>Please contact the <a href="https://students.ubc.ca/about-student-services/centre-for-accessibility">Center for Accessibility</a> if you require accommodations for a disability. Once you are registered please make me aware of any necessary accommodations by email in a timely manner.</p>
<p>I will make accommodations on a case by case basis for extenuating circumstances that prevent you completing course work. It is your responsibility to communicate your needs in a timely fashion (i.e.&nbsp;<strong>before</strong> a due date). * If you require an accommodation please contact Dr.&nbsp;June skeeter by email: june.skeeter@ubc.ca * My typical approach is to give an alternative assignment rather than giving extensions on lab quizzes because we post the answers after submission deadlines: * An alternative lab might consist of writing up an essay or two pertaining to the lecture material + making any maps/figures from the lab, then submitting directly to me by email anytime before the last day of class.</p>
</section>
<section id="academic-concessions" class="level2">
<h2 class="anchored" data-anchor-id="academic-concessions">Academic Concessions</h2>
<p>If you require an <a href="https://www.arts.ubc.ca/degree-planning/academic-performance/academic-concession/">Academic Concession</a> please email me promptly so that we can work together to figure out an accommodation for your situation. You are not obligated to explain your personal circumstances to me to justify the concession, my inent is to be accomodating. However, you must to communicate any need for a concession in a timely manner. If you require multiple concessions I may refer you to <a href="https://www.arts.ubc.ca/student-support/academic-support/academic-advising/">Arts Advising</a>.</p>
</section>
<section id="academic-integrity" class="level2">
<h2 class="anchored" data-anchor-id="academic-integrity">Academic Integrity</h2>
<p>The academic enterprise is founded on honesty, civility, and integrity. As members of this enterprise, all students are expected to know, understand, and follow the codes of conduct regarding academic integrity. At the most basic level, this means submitting only original work done by you and acknowledging all sources of information or ideas and attributing them to others as required. This also means you should not cheat, copy, or mislead others about what is your work. Violations of academic integrity (i.e., misconduct) lead to the breakdown of the academic enterprise, and therefore serious consequences arise and harsh sanctions are imposed.</p>
<p>Plagiarism and cheating will be taken very seriously. The first incident of plagiarism/copying/cheating will result in a zero for the assignment. Further incidents will be reported to the President’s Advisory Committee on Student Discipline in addition to a zero. A more detailed description of academic integrity, including the University’s policies and procedures, may be found <a href="https://learningcommons.ubc.ca/academic-integrity/Links">here</a></p>
<p>Though you may work together with your classmates on the assignments and help each other, ALL STUDENTS MUST SUBMIT THEIR OWN ORIGINAL WORK. This means that your maps must be your own, and your answers must be in your own words. Failure to submit your own work can result in failing the assignment or worse, so please be careful. See the Academic Integrity section of the Syllabus for more information.</p>
</section>
</section>
<section id="strategies-for-success" class="level1">
<h1>Strategies for Success</h1>
<p><strong>Be proactive!</strong></p>
<ul>
<li>Keep track of deadlines &amp; note the late submission policies
<ul>
<li>Timely communication is important! If you have an issue, please bring it to my attention.</li>
<li>Partial credit is better than no credit. If you can’t finish a lab before the deadline - just submit what you’ve got done already.</li>
</ul></li>
<li>Drop by office hours &amp; ask questions!</li>
<li>Don’t wait until the last minute to set up ArcGIS Pro, do it now to save yourself a headache down the road.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>